// Generates a .env with fresh random secrets. Refuses to overwrite an existing one.
// Usage: node scripts/gen-env.mjs [--force]
import { existsSync, writeFileSync } from 'node:fs';
import { randomBytes, scryptSync } from 'node:crypto';

const force = process.argv.includes('--force');
if (existsSync('.env') && !force) {
  console.error('.env already exists. Delete it or pass --force.');
  process.exit(1);
}

// URL-safe, so the credentials can be embedded in a connection string as-is.
const secret = (n) => randomBytes(n).toString('base64url');
const b64 = (n) => randomBytes(n).toString('base64');

const dbUser = 'hookrelay';
const dbName = 'hookrelay';
const dbPassword = secret(18);
const rabbitUser = 'hookrelay';
const rabbitPassword = secret(18);
const password = process.env.ADMIN_PASSWORD ?? secret(12);

// ENV_ADMIN_PASSWORD_HASH format: scrypt:<saltB64>:<hashB64> (see apps/ingest/src/auth.ts)
const salt = randomBytes(16);
const hash = scryptSync(password, salt, 32);

writeFileSync('.env', `# Generated by scripts/gen-env.mjs — do not commit.
ENV_DB_USER=${dbUser}
ENV_DB_PASSWORD=${dbPassword}
ENV_DB_NAME=${dbName}
ENV_RABBIT_USER=${rabbitUser}
ENV_RABBIT_PASSWORD=${rabbitPassword}

# For running the apps on the host. Compose rewrites these to point at the containers.
ENV_DB_URL=postgres://${dbUser}:${dbPassword}@127.0.0.1:5432/${dbName}
ENV_RABBIT_URL=amqp://${rabbitUser}:${rabbitPassword}@127.0.0.1:5672
ENV_REDIS_URL=redis://127.0.0.1:6379

ENV_MASTER_KEY=${b64(32)}
ENV_JWT_SECRET=${secret(48)}
ENV_ADMIN_TOKEN=${secret(32)}
ENV_ADMIN_PASSWORD_HASH=scrypt:${salt.toString('base64')}:${hash.toString('base64')}

ENV_PORT=3000
ENV_ALLOW_HTTP=false
ENV_SSRF_ALLOW_IPS=
ENV_ALLOWED_ORIGINS=http://127.0.0.1:5173
ENV_PUBLIC_ORIGINS=http://localhost:8080,http://127.0.0.1:8080
`);

console.log('wrote .env');
console.log(`admin password: ${password}`);
